name: c_pos
description: ""
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # Injector
  get_it: ^8.0.3

  # Design pattern
  equatable: ^2.0.7
  provider: ^6.1.2
  flutter_bloc: ^9.1.0

  # Network
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0

  # stogare
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Screen Util
  flutter_screenutil: ^5.9.3

  # Url Launcher
  url_launcher: ^6.3.0

  # Toast
  bot_toast: ^4.1.3

  # Shimmer
  shimmer: ^3.0.0

  # Flutter keyboard visibility
  flutter_keyboard_visibility: ^6.0.0

  # applink and deeplink
  app_links: ^6.4.0

  # Go router
  go_router: ^14.2.1

  # path
  path_provider: ^2.1.3
  path_provider_ios: ^2.0.11

  # Device info
  device_info_plus: ^11.1.1

  # permission
  permission_handler: ^11.3.1

  #
  uuid: ^4.5.1
  dart_jsonwebtoken: ^2.14.0
  logger: ^2.4.0

  #
  smooth_page_indicator: ^1.2.0+3
  expandable_page_view: ^1.0.17

  calendar_date_picker2: ^1.1.7
  # mat_month_picker_dialog: ^1.1.2
  month_picker_dialog: ^6.5.0

  pull_to_refresh: ^2.0.0
  webview_flutter: ^4.8.0
  toastification: ^2.1.0
  flutter_popup: ^3.3.0
  flutter_typeahead: ^5.2.0
  animated_visibility: ^0.0.4
  animated_custom_dropdown: ^3.1.1

  # Firebase
  firebase_core: ^3.12.0
  firebase_analytics: ^11.4.3

  #sentry
  sentry_flutter: ^8.14.0

  dynamic_tabbar: ^1.0.8
  timelines_plus: ^1.0.6
  data_table_2: ^2.5.15
  # google_mlkit_barcode_scanning: ^0.13.0
  qr_code_scanner_plus: ^2.0.14
  camera: ^0.10.5+9
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  mime: ^2.0.0
  collection: ^1.18.0

  cached_network_image: ^3.4.1

  #
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

  #
  connectivity_plus: ^6.1.1
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  flutter_gen_runner: ^5.9.0
  retrofit_generator:
  freezed:
  json_serializable:
  hive_generator:
  flutter_native_splash:
  flutter_launcher_icons:
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1

dependency_overrides:
  dart_style: ^2.3.0
  logging: 1.1.0

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/configuration/
    - assets/lottie/
